# pnpm-monrepo/pnpm-workspace.yaml
packages:
  - "./apps/**"
  - "./packages/**"

catalog:
  eslint: ^9.9.0
  prettier: ^3.3.3
  typescript: ^5.5.4
  zod: ^3.24.1
  dotenv-cli: ^7.4.2
  starknet: ^6.11.0
  viem: ^2.21.53
  drizzle-kit: ^0.30.1
  drizzle-orm: ^0.37
  typescript": ^5.6.2
