# pnpm-monrepo/pnpm-workspace.yaml
packages:
  - "./apps/**"
  - "./packages/**"
  - "./tooling/**"
catalog:
  eslint: ^9.9.0
  prettier: ^3.3.3
  zod: ^3.24.1
  dotenv-cli: ^7.4.2
  starknet: ^6.23.1
  viem: ^2.21.53
  drizzle-kit: ^0.30.5
  drizzle-orm: ^0.40.1
  typescript: ^5.8.2
