sources:
  - name: lordsbridge
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/{context.subgraphName:redbeardeth/starknet-bridge-mainnet}
  - name: apibara
    handler:
      graphql:
        endpoint: https://resonant-badge-production.up.railway.app/{context.apibaraHandle:graphql}
  - name: l1Realms
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/{context.realms-subgraph:bibliothecaforadventurers/realms}
documents:
  - "./queries/**/*.graphql"
