import { Provider } from "./providers/provider";
import "./globals.css";
import Sidebar from "./components/SideMenu";
import { TopNav } from "./components/TopNav";

export const metadata = {
  title: "Bibliotheca DAO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="text-white bg-theme-gray">
        <main className="flex h-screen">
          <Provider>
            <Sidebar />
            <div className="flex-grow overflow-y-scroll">
              {/* <TopNav /> */}
              {children}
            </div>
          </Provider>
        </main>
      </body>
    </html>
  );
}
