import { Provider } from "./providers/provider";
import "./globals.css";
import Sidebar from "./components/SideMenu";
import { TopNav } from "./components/TopNav";
import { Inconsolata, Karla } from "next/font/google";
import { Footer } from "./components/Footer";

const inconsolata = Inconsolata({
  subsets: ["latin"],
  variable: "--font-inconsolata",
});

const karla = Karla({
  subsets: ["latin"],
  variable: "--font-karla",
  weight: "800",
});

export const metadata = {
  title: "Bibliotheca DAO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-theme-gray ${inconsolata.variable} ${karla.variable}  text-white/80`}
      >
        <main className="flex flex-wrap h-screen">
          <Provider>
            <Sidebar />
            <div className="flex-grow ">
              <TopNav />
              {children}
            </div>
          </Provider>
          <Footer />
        </main>
      </body>
    </html>
  );
}
