name: knip

on:
  pull_request:
    paths-ignore:
      - ".github/**"
      - "pnpm-lock.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  knip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.7.0

      - name: Install dependencies
        run: pnpm i

      - name: Run knip
        run: pnpm knip
